export const KeyCode = {
    ArrowUp: "ArrowUp" ,
    ArrowDown: "ArrowDown",
    ArrowLeft: "ArrowLeft" ,
    ArrowRight: "ArrowRight" ,
    Space: "Space",
    KeyQ: "KeyQ",
    KeyW: "KeyW",
    KeyE: "KeyE",
    KeyR: "KeyR",
    KeyT: "KeyT",
    KeyY: "KeyY",
    KeyU: "KeyU",
    KeyI: "KeyI",
    KeyO: "KeyO",
    KeyP: "KeyP",
    KeyA: "KeyA",
    KeyS: "KeyS",
    KeyD: "KeyD",
    KeyF: "KeyF",
    KeyG: "KeyG",
    KeyH: "KeyH",
    KeyJ: "KeyJ",
    KeyK: "KeyK",
    KeyL: "KeyL",
    KeyZ: "KeyZ",
    KeyX: "KeyX",
    KeyC: "KeyC",
    KeyV: "KeyV",
    KeyB: "KeyB",
    KeyN: "KeyN",
    KeyM: "KeyM",
    Digit1: "Digit1",
    Digit2: "Digit2",
    Digit3: "Digit3",
    Digit4: "Digit4",
    Digit5: "Digit5",
    Digit6: "Digit6",
    Digit7: "Digit7",
    Digit8: "Digit8",
    Digit9: "Digit9",
    Digit0: "Digit0",
    Numpad1: "Numpad1",
    Numpad2: "Numpad2",
    Numpad3: "Numpad3",
    Numpad4: "Numpad4",
    Numpad5: "Numpad5",
    Numpad6: "Numpad6",
    Numpad7: "Numpad7",
    Numpad8: "Numpad8",
    Numpad9: "Numpad9",
    Numpad0: "Numpad0",
    ShiftLeft: "ShiftLeft",
    ShiftRight: "ShiftRight"
}